title = 'sapienzastudents.net'
theme = 'hugo-book'
defaultContentLanguage = 'homepage'
defaultContentLanguageInSubdir = false
enableGitInfo = true
custom_css = ["css/contributors.css", "assets/*.scss"]

[languages]
    [languages.homepage]
        # BookSearch = false
        contentDir = 'homepage'
        disabled = false
        languageName = 'Homepage'
        title = "Homepage"
        weight = 0

        [languages.homepage.params]
            contentDir = 'homepage'

    [languages.acsai]
        contentDir = 'acsai'
        disabled = false
        languageName = 'ACSAI'
        title = 'ACSAI'
        weight = 1

        [languages.acsai.params]
            contentDir = 'acsai'

    [languages.29932]
        contentDir = '29932'
        disabled = false
        languageName = 'Computer Science'
        title = 'Computer Science'
        weight = 2

        [languages.29932.params]
            contentDir = '29932'

    [languages.cybersec]
        contentDir = 'cybersec'
        disabled = false
        languageName = 'Cybersecurity'
        title = 'Cybersecurity'
        weight = 3

        [languages.cybersec.params]
        contentDir = 'cybersec'

    [languages.it]
        contentDir = 'it'
        disabled = false
        languageName = 'Informatica'
        title = 'Informatica'
        weight = 4

        [languages.it.params]
            contentDir = 'it'

    [languages.31299]
        contentDir = '31299'
        disabled = false
        languageName = 'Filosofia'
        title = 'Filosofia'
        weight = 5

        [languages.31299.params]
            contentDir = '31299'

    [languages.31774]
        contentDir = '31774'
        disabled = false
        languageName = 'Filosofia e IA'
        title = 'Filosofia e IA'
        weight = 6

        [languages.31774.params]
            contentDir = '31774'

    [languages.dev]
        contentDir = 'dev'
        disabled = true
        languageName = 'Developers Wiki'
        title = 'Developers Wiki'
        weight = 7

    [languages.rooms]
        contentDir = 'rooms'
        disabled = false
        languageName = 'Rooms'
        title = 'Rooms'
        weight = 8

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true

                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)'], ['$', '$']]

        [markup.goldmark.renderer]
            unsafe = true

[params]
    math = true
    BookTheme = 'auto'
    BookToC = true
    BookLogo = 'logo.png'
    #BookSection = '*'
    BookSection = '*'

    # GitHub Stuff
    BookRepo = 'https://github.com/sapienzastudentsnetwork/sapienzastudentsnetwork.github.io'
    BookCommitPath = 'commit'
    BookEditPath = 'edit/main'
    BookDateFormat = '2 January 2006'
